---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: envoy
  name: envoy
  namespace: projectcontour
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # This value of maxSurge means that during a rolling update
      # the new ReplicaSet will be created first.
      maxSurge: 10%
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: envoy
              topologyKey: "kubernetes.io/hostname"
            weight: 100
      containers:
        - command:
            - /bin/contour
          args:
            - envoy
            - shutdown-manager
          image: ghcr.io/projectcontour/contour:main
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/contour
                  - envoy
                  - shutdown
          name: shutdown-manager
          volumeMounts:
            - name: envoy-admin
              mountPath: /admin
        - args:
            - -c
            - /config/envoy.json
            - --service-cluster $(CONTOUR_NAMESPACE)
            - --service-node $(ENVOY_POD_NAME)
            - --log-level info
          command:
            - envoy
          image: docker.io/envoyproxy/envoy:v1.33.1