# This workflow runs Renovate on a schedule and allows manual runs.
# Renovate can be used to update dependencies that dependabot cannot.
name: Run Renovate

on:
  #schedule:
  #  - cron: "0 0 * * 0" # Weekly on Sunday at midnight.

  workflow_dispatch: # Allow manual runs.

permissions:
  contents: write # Required to push changes to the repository.
  pull-requests: write # Required to create a pull request.

env:
  GOPROXY: https://proxy.golang.org/

jobs:
  renovate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - branch: "main"
            envoy-release-track: "v1.33"
          - branch: "release-1.30"
            envoy-release-track: "v1.31"
          - branch: "release-1.29"
            envoy-release-track: "v1.30"
          - branch: "release-1.28"
            envoy-release-track: "v1.29"

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ matrix.branch }}

      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: "stable"
          cache: false

      - name: Checkout Renovate configuration from main
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: main
          path: main-branch-temp
          sparse-checkout: .github/renovate.json
          sparse-checkout-cone-mode: false

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@08ed9fa83e24bfe6222557f9e221395c57972127 # v41.0.16
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: main-branch-temp/.github/renovate.json
        env:
          LOG_LEVEL: debug
          ENVOY_RELEASE_TRACK: ${{ matrix.envoy-release-track }}
